### ISSUE TITLE
Using `percol` from `fish` shell

### ISSUE THREAD

**Issue by ghost** [mooz/percol#32]
Trying to use `percol` from `fish` as output to other commands doesn't work.

`ls | percol` works as expected.

`cd (ls | percol)` (not a typo, `fish` uses `(...)` instead of `bash`/`zsh`'s `$(...)`) closes without doing anything.

**Comment by Bastes** [comment]
Hi, I've been having this issue while using percol in a fish shell to percolate the last commit messages of git to select one for a fixup like so:

```fish
$ echo "fixup! "(git log --pretty=format:'%s' | percol)
```

What happens is, I get a blank line while a percol process is still running in the background.

This kind of behaviour (to my knowledge) happened only with percol (I tried ack, grep, head, tail, etc.). The others returned the result they should.

I also tried it in bash:

```bash
$ echo $(git log --pretty=format:'%s' | percol)
```

It works as expected.

As a percol user, I'd rather not have to use an intermediate variable like slapresta suggested (which I find rather counter-intuitive and lacking elegance for such a case), but I miss the python know-how to fiddle with the code and implement it myself as of now ^^°
