### ISSUE TITLE
Request: Customizable colors

### ISSUE THREAD

**Issue by alphapapa** [mooz/percol#66]
I like that Percol colorizes text and the selected line background, but the white-on-magenta of the selected line is not very readable on my screen, because the contrast between the text and the magenta background is not very strong.  After some digging I found where I can change the colors in `view.py`, but maintaining my own fork for this seems like overkill.

It'd be really nice if Percol supported customizable colors, perhaps by command-line options, or by a config file.

Thanks a lot for Percol!

**Comment by ibizaman** [comment]
Hi, I did not check it for myself but could this https://github.com/mooz/percol#customizing-styles be what you want?

**Comment by alphapapa** [comment]
Yes, thank you.  I don't know how I missed that.  D:
